//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.04 at 04:15:52 PM MSK 
//


package com.example.logsearch.entities;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.logsearch.entities package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResultLogs_QNAME = new QName("http://entities.logsearch.example.com", "ResultLogs");
    private final static QName _SearchInfo_QNAME = new QName("http://entities.logsearch.example.com", "SearchInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.logsearch.entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchInfo }
     * 
     */
    public SearchInfo createSearchInfo() {
        return new SearchInfo();
    }

    /**
     * Create an instance of {@link SearchInfoResult }
     * 
     */
    public SearchInfoResult createSearchInfoResult() {
        return new SearchInfoResult();
    }

    /**
     * Create an instance of {@link ResultLogs }
     * 
     */
    public ResultLogs createResultLogs() {
        return new ResultLogs();
    }

    /**
     * Create an instance of {@link SignificantDateInterval }
     * 
     */
    public SignificantDateInterval createSignificantDateInterval() {
        return new SignificantDateInterval();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultLogs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://entities.logsearch.example.com", name = "ResultLogs")
    public JAXBElement<ResultLogs> createResultLogs(ResultLogs value) {
        return new JAXBElement<ResultLogs>(_ResultLogs_QNAME, ResultLogs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://entities.logsearch.example.com", name = "SearchInfo")
    public JAXBElement<SearchInfo> createSearchInfo(SearchInfo value) {
        return new JAXBElement<SearchInfo>(_SearchInfo_QNAME, SearchInfo.class, null, value);
    }

}
